# Generated by Django 3.2.12 on 2022-03-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescriptionTopharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('Booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.booking')),
                ('PARMACY_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.pharmacy')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.doctor')),
            ],
        ),
    ]
