# Generated by Django 3.2.12 on 2022-03-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0002_prescriptiontopharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='give_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('test', models.CharField(max_length=100, null=True)),
                ('advice', models.CharField(max_length=100, null=True)),
                ('medicine_name1', models.CharField(max_length=100, null=True)),
                ('medicine1', models.CharField(max_length=100, null=True)),
                ('Quantity1', models.IntegerField(null=True)),
                ('time1', models.CharField(max_length=100, null=True)),
                ('food_time1', models.CharField(max_length=100, null=True)),
                ('medicine_name2', models.CharField(max_length=100, null=True)),
                ('medicine2', models.CharField(max_length=100, null=True)),
                ('Quantity2', models.IntegerField(null=True)),
                ('time2', models.CharField(max_length=100, null=True)),
                ('food_time2', models.CharField(max_length=100, null=True)),
                ('medicine_name3', models.CharField(max_length=100, null=True)),
                ('medicine3', models.CharField(max_length=100, null=True)),
                ('Quantity3', models.IntegerField(null=True)),
                ('time3', models.CharField(max_length=100, null=True)),
                ('food_time3', models.CharField(max_length=100, null=True)),
                ('medicine_name4', models.CharField(max_length=100, null=True)),
                ('medicine4', models.CharField(max_length=100, null=True)),
                ('Quantity4', models.IntegerField(null=True)),
                ('time4', models.CharField(max_length=100, null=True)),
                ('food_time4', models.CharField(max_length=100, null=True)),
                ('medicine_name5', models.CharField(max_length=100, null=True)),
                ('medicine5', models.CharField(max_length=100, null=True)),
                ('Quantity5', models.IntegerField(null=True)),
                ('time5', models.CharField(max_length=100, null=True)),
                ('food_time5', models.CharField(max_length=100, null=True)),
                ('medicine_name6', models.CharField(max_length=100, null=True)),
                ('medicine6', models.CharField(max_length=100, null=True)),
                ('Quantity6', models.IntegerField(null=True)),
                ('time6', models.CharField(max_length=100, null=True)),
                ('food_time6', models.CharField(max_length=100, null=True)),
                ('medicine_name7', models.CharField(max_length=100, null=True)),
                ('medicine7', models.CharField(max_length=100, null=True)),
                ('Quantity7', models.IntegerField(null=True)),
                ('time7', models.CharField(max_length=100, null=True)),
                ('food_time7', models.CharField(max_length=100, null=True)),
                ('medicine_name8', models.CharField(max_length=100, null=True)),
                ('medicine8', models.CharField(max_length=100, null=True)),
                ('Quantity8', models.IntegerField(null=True)),
                ('time8', models.CharField(max_length=100, null=True)),
                ('food_time8', models.CharField(max_length=100, null=True)),
                ('medicine_name9', models.CharField(max_length=100, null=True)),
                ('medicine9', models.CharField(max_length=100, null=True)),
                ('Quantity9', models.IntegerField(null=True)),
                ('time9', models.CharField(max_length=100, null=True)),
                ('food_time9', models.CharField(max_length=100, null=True)),
                ('Booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.booking')),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.prescription')),
            ],
        ),
    ]
