# Generated by Django 3.2.12 on 2022-03-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0003_give_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_medicine',
            name='Total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='total9',
            field=models.IntegerField(null=True),
        ),
    ]
