# Generated by Django 3.2.12 on 2022-03-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0004_auto_20220328_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_medicine',
            name='available_status1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status17',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status5',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='give_medicine',
            name='available_status9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
