# Generated by Django 3.2.12 on 2022-03-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0005_auto_20220328_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_medicine',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='not provide medicine', max_length=100, null=True),
        ),
    ]
