# Generated by Django 3.2.12 on 2022-04-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0006_auto_20220328_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEEDBACK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='COMPLAINTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=100, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.users')),
            ],
        ),
    ]
