# Generated by Django 3.2.12 on 2022-04-26 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0007_complaints_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='give_medicine',
            old_name='available_status17',
            new_name='available_status7',
        ),
    ]
