# Generated by Django 3.2.12 on 2022-04-27 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayurvedhic_app', '0008_rename_available_status17_give_medicine_available_status7'),
    ]

    operations = [
        migrations.AddField(
            model_name='give_medicine',
            name='PARMACY',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayurvedhic_app.pharmacy'),
        ),
    ]
